DEPARTMENTS = [
    "Unknown",
    "Careers",
    "Biosciences and Medicine",
    "Business School",
    "Centre for Environment and Sustainability",
    "Chemical and Process Engineering",
    "Chemistry",
    "Civil and Environmental Engineering",
    "Computer Science",
    "Economics",
    "Electrical and Electronic Engineering",
    "Guildford School of Acting",
    "Health Sciences",
    "Higher Education",
    "Hospitality and Tourism Management",
    "Law",
    "Literature and Languages",
    "Mathematics",
    "Mechanical Engineering Sciences",
    "Music and Media",
    "Physics",
    "Politics",
    "Psychology",
    "Sociology",
    "Technology Enhanced Learning",
    "Veterinary Medicine",
]
