TOPICS_ASND = [
    "Assessment: Annotated bibliography",
    "Assessment: Research proposal",
    "Assessment: Critical Article review",
    "Assessment: Presentations, Posters and digital assessment (videos etc.)",
    "Assessment: Reflective writing",
    "Assessment: Writing (reports, essays, etc.), incl. structure, paraphrasing, linking, clarity, concision, citation)",
    "Assessment: Writing a literature review",
    "Assessment process/task: Assignment planning",
    "Assessment process/task: Choosing topic/finding focus (dissertations)",
    "Assessment process/task: Interpreting criteria",
    "Assessment process/task: Interpreting feedback",
    "Assessment process/task: Interpreting Turnitin reports",
    "Assessment process/task: Literature surveys and systematic reviews",
    "Assessment process/task: Referencing",
    "Assessment process/task: Search strategies/identifying literature",
    "Assessment process/task: Sourcing and selecting evidence",
    "Academic Skills: Academic integrity referral",
    "Academic Skills: Group or teamworking, peer-based learning",
    "Academic Skills: Planning and organising time",
    "Academic Skills: Reading and note-making strategies",
    "Academic Skills: Using referencing software",
    "Academic Skills: Research design / methods/ology",
    "Academic Skills: Revision and exam strategies",
    "Critical thinking: Analysis/Writing (synthesis, evaluation, argument, position, voice)",
    "Critical thinking: Evaluating information/engaging with literature",
    "Critical thinking: Using evaluative judgement (making sense, making meaning)",
    "Learning journey: Service introduction for new students",
    "Learning journey: Transition between years/PTY/professional statements or applications",
    "Learning journey: Transition to university/UK academic setting",
]

TOPICS_MASA = [
    "Maths: Algebra",
    "Maths: Calculus",
    "Maths: Complex Numbers",
    "Maths: Numeracy",
    "Maths: Trigonometry",
    "Maths: Other",
    "Statistics: Data Collection/Handling",
    "Statistics: Data Presentation/Writing Up Results",
    "Statistics: Statistical Testing",
    "Statistics: Statistical Theory",
    "Statistics: Probability",
    "Statistics: Sample Size Calculations",
    "Statistics: Understanding Research Papers",
    "Statistics: Other",
    "Software: Excel",
    "Software: GraphPad",
    "Software: Jamovi",
    "Software: Matlab",
    "Software: R",
    "Software: SPSS",
    "Software: Other",
]
