FROM ghcr.io/xtruder/nix-devcontainer:latest

# RUN echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf

# RUN nix-env -iA \
#     nixpkgs.direnv \
#     nixpkgs.git \
#     nixpkgs.gitAndTools.gh
# RUN echo 'eval "$(direnv hook bash)"' >> ~/.bashrc
# RUN direnv allow .

ENV DIRENV_LOG_FORMAT=
